# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdcfc898b686cc4de5bcdccb2cbefd59f4ed6411c17b6d5885e015548ea8de843f6e34ee9bf361ed85cc21fd70d75f88bb1762a557066986c3983094eb5de158

test:
  secret_key_base: a4581dc0eef02b1cacfa2ade91ae0c006135820c0ffd65cf96708309c261ab2a6bd24622aa5f8fd77138e6c39c9695a35c2aa9474c2b20a95f68129fd5669c7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
